# This is a basic workflow to show https://github.com/kubernetes-sigs/kubebuilder/issues/4546 is valid issue
# As long as this workflow fails, issue is not resolved.

name: kubebuilder4546

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # probably not required
      - name: install latest docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          ls -la
          rm get-docker.sh
      - name: get docker version
        run: docker version
      # Make buildx the default build system
      - run: docker buildx install
      - run: docker buildx create --name=container --driver=docker-container --use --bootstrap
      - run: docker builder ls
      - run: |
          curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
          chmod +x kubebuilder && sudo mv kubebuilder /usr/local/bin/
      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - run: go mod init example.com/kubepusher
      - run: kubebuilder init && mkdir internal && mkdir api
      - run: make docker-build docker-push IMG=ghcr.io/kaovilai/bugreport:kubebuilder4546
      # Commenting out so it's explicitly ends here on failure to be super clear that docker-build on default scaffold has an issue, not buildx
      #   continue-on-error: true
      # - name: add docker-build-load target
      #   run: |
      #     echo '
      #     .PHONY: docker-build
      #     docker-build-load: test ## Build docker image with the manager.
      #     	docker build --load -t ${IMG} .
      #     ' >> Makefile
      # - run: make docker-build-load docker-push IMG=ghcr.io/kaovilai/bugreport:kubebuilder4546
      
